# Generated by Django 4.0.4 on 2022-06-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_vote_post_members_vote_post_vote_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
    ]
